### ISSUE TITLE
MainHeader needs to be converted to a flexbox or normal header instead of a grid

### ISSUE THREAD

**Issue by abhinavsaurav** [abhinavsaurav/kirana-store#7]
Grid is causing unintended changes while zooming down. Can be seen below.

![image](https://user-images.githubusercontent.com/25846741/150690340-5acfc71a-699b-4c75-bcad-37a95650df4e.png)

Expected behaviour should be something like on zooming out the contents of the header stay in the middle and get scaled down probably for eg: zooming out on stackoerflow.com

![image](https://user-images.githubusercontent.com/25846741/150690712-a950f3d7-db45-4820-8e79-d2f58a7cccee.png)

**Comment by GoOsTT** [comment]
Hey,

I have fixed this issue, can you please assign this issue to me please?

**Comment by abhinavsaurav** [comment]
Hi @GoOsTT ,

Thanks for your help! I have assigned this to you.

**Comment by abhinavsaurav** [comment]
@GoOsTT  Did you see the comment on your pull request? Just checking,  if you managed to fix it?

**Comment by abhinavsaurav** [comment]
Closing this issue as fixed in #15
